{% set name = "samurai" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpc-maths/samurai/archive/v{{ version }}.tar.gz
  sha256: 07971b2c5359cc33f5e3fb3f4f7d156b6aed91441139a1ae133378ba25e46d7a
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - xtensor >=0.26
    - highfive >=3
    - fmt
    - pugixml
    - cli11 <2.5
  run:
    - xtensor >=0.26
    - highfive >=3
    - fmt
    - pugixml
    - cli11 <2.5

test:
  commands:
    - test -d ${PREFIX}/include/samurai  # [unix]
    - test -f ${PREFIX}/include/samurai/field.hpp  # [unix]
    - test -f ${PREFIX}/share/samurai/samuraiConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/samurai/samuraiConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\samurai\field.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\samurai\samuraiConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\samurai\samuraiConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/hpc-maths/samurai
  summary: Intervals coupled with algebra of set to handle adaptive mesh refinement and operators on it
  description: |
    samurai allows to implement several mesh adaptation methods (patch-based, cell-based, point-based)
    from the same data structure. The mesh is represented as intervals and a set algebra allows to efficiently
    search for subsets among these intervals. Samurai also offers a flexible and pleasant interface to easily
    implement numerical methods.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://hpc-math-samurai.readthedocs.io

extra:
  recipe-maintainers:
    - gouarin
    - pmatalon
