schema_version: 1

context:
  name: samurai
  version: "0.29.2"
  _fmt: ${{ fmt }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # curl -L "https://github.com/hpc-maths/samurai/archive/v0.29.2.tar.gz" -o /tmp/samurai-0.29.2.tar.gz && shasum -a 256 /tmp/samurai-0.29.2.tar.gz
  url: https://github.com/hpc-maths/samurai/archive/v${{ version }}.tar.gz
  sha256: 7816f4269b6b93410d2d89ab65ada793317d5fa08b5f5b8a0e6e83e109d564a0

build:
  number: 4

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: ninja
  host:
    - xtensor >=0.26
    - highfive >=3
    - fmt
    - zlib
    - pugixml
    - cli11 <2.5
  run:
    - xtensor >=0.26
    - highfive >=3
    - fmt
    - zlib
    - pugixml
    - cli11 <2.5

tests:
  - script:
      - if: unix
        then: test -d ${PREFIX}/include/samurai
      - if: unix
        then: test -f ${PREFIX}/include/samurai/field.hpp
      - if: unix
        then: test -f ${PREFIX}/share/samurai/samuraiConfig.cmake
      - if: unix
        then: test -f ${PREFIX}/share/samurai/samuraiConfigVersion.cmake
      - if: win
        then: if not exist %LIBRARY_PREFIX%\include\samurai\field.hpp (exit 1)
      - if: win
        then: if not exist %LIBRARY_PREFIX%\share\samurai\samuraiConfig.cmake (exit 1)
      - if: win
        then: if not exist %LIBRARY_PREFIX%\share\samurai\samuraiConfigVersion.cmake (exit 1)

about:
  summary: Intervals coupled with algebra of set to handle adaptive mesh refinement and operators on it
  description: |
    samurai allows to implement several mesh adaptation methods (patch-based, cell-based, point-based)
    from the same data structure. The mesh is represented as intervals and a set algebra allows to efficiently
    search for subsets among these intervals. Samurai also offers a flexible and pleasant interface to easily
    implement numerical methods.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/hpc-maths/samurai
  documentation: https://hpc-math-samurai.readthedocs.io

extra:
  recipe-maintainers:
    - gouarin
    - pmatalon
